# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

name: Lint and Test - Unbundled

env:
  VSOMEIP_RELEASE_URL: https://github.com/COVESA/vsomeip/archive/refs/tags/
  VSOMEIP_RELEASE_TAG: 3.4.10.tar.gz
  VSOMEIP_SOURCE_PATH: vsomeip-src
  VSOMEIP_INSTALL_PATH: vsomeip-install

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - ".github/**"
      - "**/src/**"
      - "**/Cargo.*"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  set-env:
    name: Set environment variables
    runs-on: ubuntu-22.04

    outputs:
      arch_specific_cpp_stdlib_path: ${{ steps.set_env.outputs.arch_specific_cpp_stdlib_path }}
      generic_cpp_stdlib_path: ${{ steps.set_env.outputs.generic_cpp_stdlib_path }}

    steps:
      - uses: actions/checkout@v4

      - name: Add execute permissions for envsetup
        run: chmod +x build/envsetup.sh

      - name: Set stdlib paths dynamically
        id: set_env
        run: |
          source ./build/envsetup.sh highest
          echo "arch_specific_cpp_stdlib_path=$ARCH_SPECIFIC_CPP_STDLIB_PATH" >> $GITHUB_OUTPUT
          echo "generic_cpp_stdlib_path=$GENERIC_CPP_STDLIB_PATH" >> $GITHUB_OUTPUT

  obtain_and_build_vsomeip:
    needs: set-env
    runs-on: ubuntu-22.04
    outputs:
      cache_key: ${{ steps.generate_cache_key.outputs.CACHE_KEY }}

    env:
      ARCH_SPECIFIC_CPP_STDLIB_PATH: ${{ needs.set-env.outputs.arch_specific_cpp_stdlib_path }}
      GENERIC_CPP_STDLIB_PATH: ${{ needs.set-env.outputs.generic_cpp_stdlib_path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "VSOMEIP_SOURCE_TARBALL=${{ env.VSOMEIP_RELEASE_URL }}${{ env.VSOMEIP_RELEASE_TAG }}" >> $GITHUB_ENV
          echo "VSOMEIP_SOURCE_PATH=${{ github.workspace }}/${{ env.VSOMEIP_SOURCE_PATH }}" >> $GITHUB_ENV
          echo "VSOMEIP_INSTALL_PATH=${{ github.workspace }}/${{ env.VSOMEIP_INSTALL_PATH }}" >> $GITHUB_ENV
          echo "VSOMEIP_SOURCE_PATH_WITH_WILDCARD=${{ github.workspace }}/${{ env.VSOMEIP_SOURCE_PATH }}/*" >> $GITHUB_ENV
          env

      - name: Print environment variables for debugging
        run: |
          echo "VSOMEIP_SOURCE_TARBALL: ${{ env.VSOMEIP_SOURCE_TARBALL }}"
          echo "VSOMEIP_SOURCE_PATH: ${{ env.VSOMEIP_SOURCE_PATH }}"
          echo "VSOMEIP_INSTALL_PATH: ${{ env.VSOMEIP_INSTALL_PATH }}"
          echo "VSOMEIP_SOURCE_PATH_WITH_WILDCARD: ${{ env.VSOMEIP_SOURCE_PATH_WITH_WILDCARD }}"
          echo "GENERIC_CPP_STDLIB_PATH: ${{ env.GENERIC_CPP_STDLIB_PATH }}"
          echo "ARCH_SPECIFIC_CPP_STDLIB_PATH: ${{ env.ARCH_SPECIFIC_CPP_STDLIB_PATH }}"
          env

      - name: Download tarball
        run: |
          wget -O vsomeip-source.tar.gz $VSOMEIP_SOURCE_TARBALL
          ls -l

      - name: Create destination directory
        run: |
          mkdir -p $VSOMEIP_SOURCE_PATH
          ls -l

      - name: Decompress tarball
        run: |
          tar --strip-components=1 -xzf vsomeip-source.tar.gz -C $VSOMEIP_SOURCE_PATH
          ls -l

      - name: Confirm decompressed
        run: |
          echo "Current working directory: $(pwd)"
          echo "Contents of repository root:"
          ls -l
          echo "Contents of decompressed folder ($VSOMEIP_SOURCE_PATH):"
          ls -l $VSOMEIP_SOURCE_PATH

      - name: Generate cache key
        run: echo "CACHE_KEY=${{ runner.os }}-vsomeip-${{ hashFiles(env.VSOMEIP_SOURCE_PATH_WITH_WILDCARD) }}" >> $GITHUB_ENV

      - name: Set cache key output
        id: generate_cache_key
        run: echo "CACHE_KEY=${{ env.CACHE_KEY }}" >> $GITHUB_OUTPUT

      - name: Cache vsomeip build
        id: cache-vsomeip
        uses: actions/cache@v3
        with:
          path: ${{ env.VSOMEIP_INSTALL_PATH }}
          key: ${{ runner.os }}-vsomeip-${{ hashFiles(env.VSOMEIP_SOURCE_PATH_WITH_WILDCARD) }}
          restore-keys: |
            ${{ runner.os }}-vsomeip-

      - name: Install dependencies
        if: steps.cache-vsomeip.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libboost-all-dev doxygen asciidoc

      - name: Build vsomeip
        if: steps.cache-vsomeip.outputs.cache-hit != 'true'
        run: |
          cd $VSOMEIP_SOURCE_PATH
          cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$VSOMEIP_INSTALL_PATH -DENABLE_SIGNAL_HANDLING=1 .
          cmake --build build --target install

      - name: Save vsomeip build to cache
        if: steps.cache-vsomeip.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: ${{ env.VSOMEIP_INSTALL_PATH }}
          key: ${{ runner.os }}-vsomeip-${{ hashFiles(env.VSOMEIP_SOURCE_PATH_WITH_WILDCARD) }}

  lint:
    name: Lint
    needs:
      - set-env
      - obtain_and_build_vsomeip
    runs-on: ubuntu-22.04
    env:
      ARCH_SPECIFIC_CPP_STDLIB_PATH: ${{ needs.set-env.outputs.arch_specific_cpp_stdlib_path }}
      GENERIC_CPP_STDLIB_PATH: ${{ needs.set-env.outputs.generic_cpp_stdlib_path }}
      CACHE_KEY: ${{ needs.obtain_and_build_vsomeip.outputs.cache_key }}

    steps:
      - uses: actions/checkout@v4

      - name: Install C++ dependencies
        run: sudo apt-get install -y build-essential cmake libboost-all-dev

      - name: Set environment variables
        run: |
          echo "VSOMEIP_INSTALL_PATH=${{ github.workspace }}/${{ env.VSOMEIP_INSTALL_PATH }}" >> $GITHUB_ENV

      - name: Print environment variables for debugging
        run: |
          echo "VSOMEIP_INSTALL_PATH: ${{ env.VSOMEIP_INSTALL_PATH }}"

      - name: Ensure vsomeip install path exists
        run: |
          mkdir -p ${{ env.VSOMEIP_INSTALL_PATH }}
          ls -l

      - name: Print cache_key
        run: |
          echo "cache_key: ${{ env.CACHE_KEY }}"

      - name: Restore vsomeip build cache
        uses: actions/cache@v3
        with:
          path: ${{ env.VSOMEIP_INSTALL_PATH }}
          key: ${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-vsomeip-

      - name: Install stable toolchain
        run: |
          rustup show
          rustup component add rustfmt clippy

      - name: Build the project without Zenoh & vsomeip transports
        working-directory: ${{github.workspace}}
        run: cargo build
      - name: cargo clippy without Zenoh & vsomeip transports
        working-directory: ${{github.workspace}}
        run: cargo clippy --all-targets -- -W warnings -D warnings
      - name: Build the project with Zenoh & vsomeip transports (and thus streamer references)
        working-directory: ${{github.workspace}}
        run: cargo build --features vsomeip-transport,zenoh-transport,mqtt-transport
      - name: cargo clippy with Zenoh & vsomeip transports (and thus streamer references)
        working-directory: ${{github.workspace}}
        run: cargo clippy --features vsomeip-transport,zenoh-transport,mqtt-transport --all-targets -- -W warnings -D warnings
      - name: cargo fmt
        working-directory: ${{github.workspace}}
        run: cargo fmt -- --check

  test:
    name: Test
    needs:
      - set-env
      - obtain_and_build_vsomeip
    runs-on: ubuntu-22.04

    env:
      ARCH_SPECIFIC_CPP_STDLIB_PATH: ${{ needs.set-env.outputs.arch_specific_cpp_stdlib_path }}
      GENERIC_CPP_STDLIB_PATH: ${{ needs.set-env.outputs.generic_cpp_stdlib_path }}
      CACHE_KEY: ${{ needs.obtain_and_build_vsomeip.outputs.cache_key }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install C++ dependencies
        if: steps.cache-vsomeip.outputs.cache-hit != 'true'
        run: sudo apt-get install -y build-essential cmake libboost-all-dev

      - name: Set environment variables
        run: |
          echo "VSOMEIP_INSTALL_PATH=${{ github.workspace }}/${{ env.VSOMEIP_INSTALL_PATH }}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ github.workspace }}/${{ env.VSOMEIP_INSTALL_PATH }}/lib" >> $GITHUB_ENV

      - name: Print environment variables for debugging
        run: |
          echo "VSOMEIP_INSTALL_PATH: ${{ env.VSOMEIP_INSTALL_PATH }}"
          echo "LD_LIBRARY_PATH: ${{ env.LD_LIBRARY_PATH }}"

      - name: Ensure vsomeip install path exists
        run: |
          mkdir -p ${{ env.VSOMEIP_INSTALL_PATH }}
          ls -l

      - name: Print cache_key
        run: |
          echo "cache_key: ${{ env.CACHE_KEY }}"

      - name: Restore vsomeip build cache
        uses: actions/cache@v3
        with:
          path: ${{ env.VSOMEIP_INSTALL_PATH }}
          key: ${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-vsomeip-

      - name: Show toolchain information
        working-directory: ${{github.workspace}}
        run: |
          rustup toolchain list
          cargo --version
      - name: Run tests
        run: |
          LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${VSOMEIP_INSTALL_PATH}/lib cargo test --no-default-features --doc --tests -- --test-threads 1

  build-docs:
    name: Build documentation
    needs:
      - obtain_and_build_vsomeip
      - set-env
    runs-on: ubuntu-22.04
    env:
      ARCH_SPECIFIC_CPP_STDLIB_PATH: ${{ needs.set-env.outputs.arch_specific_cpp_stdlib_path }}
      GENERIC_CPP_STDLIB_PATH: ${{ needs.set-env.outputs.generic_cpp_stdlib_path }}
      CACHE_KEY: ${{ needs.obtain_and_build_vsomeip.outputs.cache_key }}

    steps:
      - uses: actions/checkout@v4

      - name: Install C++ dependencies
        run: sudo apt-get install -y build-essential cmake libboost-all-dev

      - name: Set environment variables
        run: |
          echo "VSOMEIP_INSTALL_PATH=${{ github.workspace }}/${{ env.VSOMEIP_INSTALL_PATH }}" >> $GITHUB_ENV

      - name: Print environment variables for debugging
        run: |
          echo "VSOMEIP_INSTALL_PATH: ${{ env.VSOMEIP_INSTALL_PATH }}"

      - name: Ensure vsomeip install path exists
        run: |
          mkdir -p ${{ env.VSOMEIP_INSTALL_PATH }}
          ls -l

      - name: Print cache_key
        run: |
          echo "cache_key: ${{ env.CACHE_KEY }}"

      - name: Restore vsomeip build cache
        uses: actions/cache@v3
        with:
          path: ${{ env.VSOMEIP_INSTALL_PATH }}
          key: ${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-vsomeip-

      - name: Create Documentation for up-streamer
        working-directory: ${{github.workspace}}
        run: RUSTDOCFLAGS=-Dwarnings cargo doc -p up-streamer --no-deps --no-default-features

      - name: Create Documentation for up-linux-streamer
        working-directory: ${{github.workspace}}
        run: RUSTDOCFLAGS=-Dwarnings cargo doc -p up-linux-streamer --no-deps --no-default-features
